#property images
from tkinter import *

from PIL import Image,ImageTk
Mediterranean_Avenue= Image.open("mediterranean ave.png")
Baltic_Avenue= Image.open("baltic ave.png")
Reading_Railroad= Image.open("reading railroad.png")
Oriental_Avenue= Image.open("oriental ave.png")
Vermont_Avenue= Image.open("vermont ave.png")
Connecticut_Avenue= Image.open("connecticut ave.png")
StCharles_Place= Image.open("st charles place.png")
Electric_Company= Image.open("electric company.png")
States_Avenue= Image.open("states ave.png")
Virginia_Avenue= Image.open("virginia ave.png")
Pennsylvania_Railroad= Image.open("pennsylvania rr.png")
StJames_Place= Image.open("st james place.png")
Tennessee_Avenue= Image.open("tennessee av.png")
New_York_Avenue= Image.open("new york ave.png")
Kentucky_Avenue = Image.open("kentucky ave.png")
Indiana_Avenue= Image.open("indiana ave.png")
Illinois_Avenue= Image.open("illinois ave.png")
BO_Railroad= Image.open("b. & o. railroad.png")
Atlantic_Avenue= Image.open("atlantic ave.png")
Ventnor_Avenue= Image.open("ventnor ave.png")
Water_Works= Image.open("water works.png")
Marvin_Gardens= Image.open("marvin gardens.png")
Pacific_Avenue= Image.open("pacific ave.png")
North_Carolina_Avenue= Image.open("no calorina ave.png")
Pennsylvania_Avenue= Image.open("pennsylvania ave.png")
Short_Line= Image.open("short line rr.png")
Park_Place= Image.open("park place.png")
Boardwalk= Image.open("boardwalk.png")